services:
  postgres:
    image: postgres:15
    container_name: iagen-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  back:
    container_name: iagen-back
    restart: unless-stopped
    build:
      context: ./iagen-reclamacoes-api
      dockerfile: src/main/docker/Dockerfile
    env_file:
      - .env
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: ${QUARKUS_DATASOURCE_JDBC_URL}
      QUARKUS_DATASOURCE_USERNAME: ${QUARKUS_DATASOURCE_USERNAME}
      QUARKUS_DATASOURCE_PASSWORD: ${QUARKUS_DATASOURCE_PASSWORD}
      QUARKUS_HTTP_PORT: ${QUARKUS_HTTP_PORT}
      QUARKUS_LANGCHAIN4J_GEMINI_API_KEY: ${QUARKUS_LANGCHAIN4J_GEMINI_API_KEY}
    ports:
      - "${BACK_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy

  front:
    container_name: iagen-front
    restart: unless-stopped
    build:
      context: ./iagen-reclamacoes-web
      dockerfile: Dockerfile
      args:
        API_BASE_URL: ${FRONT_API_BASE_URL}
    ports:
      - "${FRONT_PORT}:80"
    depends_on:
      - back

volumes:
  pgdata:
